version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "14:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 0
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "14:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 3
